### ISSUE TITLE
Offset

### ISSUE THREAD

**Issue by amandalmia14** [vaibhavad/python-wrapper-OpenIE5#1]
Hi @vaibhavad ,

Can you please elaborate more on the offset with an example?

Thanks.

**Comment by vaibhavad** [comment]
Hi @amandalmia14,

The offsets are used internally in OpenIE and we plan to remove it from JSON response in our next update. OpenIE works best on simple sentences. To facilitate that, a module breaks conjunctive sentences to simple ones and then runs extractions on them. The offsets correspond to these simple sentences. To just give an insight into how offsets are used - 

"He entered the Society of Jesus on 7 September 1630 and was sent to the English missions in 1640 ." is split into "He entered the Society of Jesus on 7 September 1630" and "He was sent to the English missions in 1640 ."

You'll see the offsets in the extractions corresponding to these sentences rather than the original sentence.

Regards,
Vaibhav
