### ISSUE TITLE
How to get SRL result in retrieved triples ?

### ISSUE THREAD

**Issue by therealhieu** [vaibhavad/python-wrapper-OpenIE5#7]
![image](https://user-images.githubusercontent.com/38937534/94550574-241dce00-027e-11eb-9b46-4f0df46fe9c1.png)
HttpResponse receive through API server currently does not contain SRL arguments (SpatialArgument and TemporalArgument).

Can you guide me a way to get those arguments?

**Comment by aliozts** [comment]
I'd like to know as well.

**Comment by glory-99** [comment]
I'd like to know, too.

**Comment by aliozts** [comment]
Hello @glory-99 and @hieudepchai , I am not a scala developer by no means so please take what I'll say with a pinch of salt, but I have came up with something

After checking the code, I have found out that what we see in the response is the class variables for the `Argument` in `Extraction.scala` (path is in the first section). For the `Spatial` and `Temporal` locations, the `displayText` parameter is changed so that when it is displayed (check the code that it is in the top of `Extraction.scala`. It will be printed respectively. So what I did is just adding an attribute `typ` to the class and changed it in the others,

1. Find the src/main/scala/edu/knowitall/openie/Extraction.scala
2. Change the `Argument` class to
```
abstract class Argument extends Part{
  val typ = "Simple"
}
```

3. Add the `typ` (name it whatever you want, that will be what you'll see next to `text` in your http response

```
case class SpatialArgument(text: String, offsets: Seq[Interval]) extends Argument {
  override def displayText = "L:" + text

  override val typ = "Spatial"
}

case class TemporalArgument(text: String, offsets: Seq[Interval]) extends Argument {
  override def displayText = "T:" + text

  override val typ = "Temporal"
}
```

After doing this, you need to recompile etc. and it should work, i guess

**Comment by glory-99** [comment]
> Hello @glory-99 and @hieudepchai , I am not a scala developer by no means so please take what I'll say with a pinch of salt, but I have came up with something
> 
> After checking the code, I have found out that what we see in the response is the class variables for the `Argument` in `Extraction.scala` (path is in the first section). For the `Spatial` and `Temporal` locations, the `displayText` parameter is changed so that when it is displayed (check the code that it is in the top of `Extraction.scala`. It will be printed respectively. So what I did is just adding an attribute `typ` to the class and changed it in the others,
> 
> 1. Find the src/main/scala/edu/knowitall/openie/Extraction.scala
> 2. Change the `Argument` class to
> 
> ```
> abstract class Argument extends Part{
>   val typ = "Simple"
> }
> ```
> 
> 1. Add the `typ` (name it whatever you want, that will be what you'll see next to `text` in your http response
> 
> ```
> case class SpatialArgument(text: String, offsets: Seq[Interval]) extends Argument {
>   override def displayText = "L:" + text
> 
>   override val typ = "Spatial"
> }
> 
> case class TemporalArgument(text: String, offsets: Seq[Interval]) extends Argument {
>   override def displayText = "T:" + text
> 
>   override val typ = "Temporal"
> }
> ```
> 
> After doing this, you need to recompile etc. and it should work, i guess

I'll have a try, thanks!
